### PR TITLE
Mark component as abandoned

### PR DESCRIPTION
**Pull request by froschdesign**
The custom properties of this repository are also updated.

### CODE REVIEW

**Comment by froschdesign** [comment]
@gsteel 
Support for version 8.4 is missing in this component.

**Review by gsteel — APPROVED** [review]
👍

**Comment by gsteel** [comment]
Sorry @froschdesign I've been going through the abandoned repos on autopilot and forgot this patch was here and just merged #12 

Before I release 2.11.1 - were you expecting to add 8.4 support - IMO we shouldn't bother

**Comment by froschdesign** [comment]
> IMO we shouldn't bother

👍🏻

**Pull request closed without merging**
